#Schema
"$schema" = 'https://starship.rs/config-schema.json'

# Basic Options
add_newline = false

[hostname]
ssh_only = false
format = "[$hostname -> ](bold red)"

[username]
show_always = true
format = "@[$user-](bold yellow)"

[directory]
truncation_symbol = '~/'

[package]
disabled = true
