#Basic Settings
set -g default-terminal "screen-256color"
set -g mouse off
set -s escape-time 0
set -g repeat-time 0

source ~/.config/tmux/statusbar.conf
source ~/.config/tmux/colors.conf
# source ~/.config/tmux/takuya-theme.conf # Custom Tmux Statusbar Setup

#Remapping Leader Key to <Ctrl-s>
set -g prefix C-s
unbind C-b
bind-key C-s send-prefix

# Basic PopUp Window Keybinds
bind -r g display-popup 

#Horizontal Splitting
unbind %
bind | split-window -h 

#Vertical Splitting
unbind '"'
bind - split-window -v

#Keymap for Reloading Tmux Config
unbind r
bind r source-file ~/.config/tmux/.tmux.conf \; display-message "Config Successfully Reloaded!"

#Toggle Maximize Pane
bind -r m resize-pane -Z

#Enabeling Vim Type Keymapping
bind -r C-k resize-pane -U 2
bind -r C-j resize-pane -D 2
bind -r C-h resize-pane -L 2
bind -r C-l resize-pane -R 2

bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 
unbind Up     
unbind Down   
unbind Left   
unbind Right  
unbind C-Up   
unbind C-Down 
unbind C-Left 
unbind C-Right

#Plugin Manager And Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'niksingh710/minimal-tmux-status'

# Theme Setup
set -g @minimal-tmux-bg "#698DDA"
set -g @minimal-tmux-status-right "#(whoami) "
set -g @minimal-tmux-justify "left"
set -g @minimal-tmux-indicator false

#Enabling Plugins
run '~/.tmux/plugins/tpm/tpm'
