#Basic Settings
set -g default-terminal "screen-256color"
set -g mouse off
set -s escape-time 0
set -g repeat-time 0

source ~/.config/tmux/statusbar.conf
source ~/.config/tmux/colors.conf

#Remapping Leader Key to <Ctrl-s>
set -g prefix C-s
unbind C-b
bind-key C-s send-prefix

#Horizontal Splitting
unbind %
bind | split-window -h 

#Vertical Splitting
unbind '"'
bind - split-window -v

#Keymap for Reloading Tmux Config
unbind r
bind r source-file ~/.config/tmux/.tmux.conf \; display-message "Config Successfully Reloaded!"

#Toggle Maximize Pane
bind -r m resize-pane -Z

#Enabeling Vim Type Keymapping
bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 
unbind Up     
unbind Down   
unbind Left   
unbind Right  
unbind C-Up   
unbind C-Down 
unbind C-Left 
unbind C-Right

#Plugin Manager And Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'catppuccin/tmux'

#Enabling Plugins
run '~/.tmux/plugins/tpm/tpm'
