#Basic Settings
set -g default-terminal "screen-256color"
set -g mouse on
set -s escape-time 0

#StatusBar Config
set-option -g status-position bottom
set-option -g automatic-rename off
set -g @themepack-status-right-area-left-format ""
set -g @themepack-status-right-area-middle-format ""
set -g @themepack-status-right-area-right-format ""

#Remapping Leader Key to <Ctrl-s>
set -g prefix C-s
unbind C-b
bind-key C-s send-prefix

#Horizontal Splitting
unbind %
bind | split-window -h 

#Vertical Splitting
unbind '"'
bind - split-window -v

#Keymap for Reloading Tmux Config
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config Successfully Reloaded!"

#Toggle Maximize Pane
bind -r m resize-pane -Z

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jimeh/tmux-themepack'

#Plugins Setup
set -g @themepack 'powerline/block/cyan'

#Enabling Plugins
run '~/.tmux/plugins/tpm/tpm'
